---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Introduction
This assignment makes use of data from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.

## Data
The data for this assignment can be downloaded from the course web site.

The variables included in this dataset are:

* **steps**: Number of steps taking in a 5-minute interval (missing values are coded as `NA`)

* **date**: The date on which the measurement was taken in YYYY-MM-DD     format

* **interval**: Identifier for the 5-minute interval in which     measurement was taken

The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this dataset.

# At first, we remove all variables from environment
rm(list=ls(all=TRUE))

# Then we get file with data from URL
FileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"

if (!file.exists("repdata-data-activity.zip")) {
   download.file(FileUrl, destfile = "repdata-data-activity.zip")
}
unzip("repdata-data-activity.zip")

## Assignment

### Loading and preprocessing the data
# Load the data
activity_data <-
    read.csv('activity.csv', header = T)

# Process/transform the data (if necessary) into a format suitable for your analysis
activity_data$date <- 
    as.Date(activity_data$date)

### What is mean total number of steps taken per day?
For this part of the assignment we ignore the missing values in the dataset.

#### Make a histogram of the total number of steps taken each day
# At first, we set locale to English
Sys.setlocale("LC_TIME", "English")

# Summarize the total number of steps taken by each day
StepsByDay <-
   aggregate(x = activity_data$steps,
             by = list(activity_data$date),
             FUN = sum,
             na.rm = T)
names(StepsByDay) <- c("date","steps")

hist(StepsByDay$steps, 
     breaks = 20,
     main = "Histogram of steps taken each day",
     xlab = 'Total Number of Steps',
     col = 'grey')

#### Calculate and report the **mean** and **median** total number of steps taken per day
#calculate mean and median total number of steps taken per day
mean_steps = round(mean(StepsByDay$steps), 2)
median_steps = round(median(StepsByDay$steps), 2)

#draw lines for mean and median
abline(v = mean_steps, lwd = 3, col = 'blue')
abline(v = median_steps, lwd = 3, col = 'red')

#place legend
legend('topright',
       lty = 1,
       lwd = 3,
       col = c("blue", "red"),
       cex = .8, 
       legend = c(paste('Mean: ', mean_steps),
       paste('Median: ', median_steps))
       )

### What is the average daily activity pattern?



### Imputing missing values



### Are there differences in activity patterns between weekdays and weekends?
